### ISSUE TITLE
Module published on the Gladys store! 

### ISSUE THREAD

**Issue by Pierre-Gilles** [atrovato/gladys-awox#1]
Hey,

First: Congrats on your module 🙌Good work :)

I've accepted the module on the store. 

https://developer.gladysproject.com/en/modules/awox

One thing, can you now write your installation instructions in french as well? otherwise it will not appear on the french store^^

Thanks!

**Comment by atrovato** [comment]
Youpi !!! Ok je le fais ASAP.
Merci :)

**Comment by atrovato** [comment]
French description provided. Thx

**Comment by atrovato** [comment]
@Pierre-Gilles Pourras-tu penser à rendre le module disponible sur le french store ?
Petite tâche Trello ?!

Merci

**Comment by Pierre-Gilles** [comment]
Hello! Désolé pour la réponse lente, mon github est plein de notifications c'est jamais facile à gérer :D 

Alors bizarrement je n'ai jamais eu de texte en version française pour ce module...

Du coup ce que j'ai fais, j'ai dupliqué la version anglaise, et je l'ai mis dans la française, comme ça de ton côté tu peux éditer sur le store developer. 

Dis moi quand tu as traduis et je déploie ça sur toutes les instances!

**Comment by atrovato** [comment]
Mince alors, pourtant j'avais édité la version 0.0.5 du module, celle qui tu avais validée. 
J'espère ne pas avoir perdu les modifications, j'avais fourni une description plus complète. 
Je te tiens au jus dès que la description est à jour. 
Merci de l'avoir traduite de l'anglais.

**Comment by atrovato** [comment]
Je viens de modifier la traduction en français (et anglais), tout a fonctionné.
Merci pour tout ;)
