### ISSUE TITLE
Integrate state feedback

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#10]
After sending a request to the bulb, check if the command has been received, and well interpreted : check if the new status is correct.
Might be related to #9

**Comment by atrovato** [comment]
Did you find any issue to create this point ?
Usually, the Gladys device state changes only if the Bluetooth message is well managed, but I assume to not check the bulb state, I trust the command sent by Gladys.

**Comment by pebou** [comment]
After further investigations, it might be a more Gladys (Gateway) issue.
Gladys doesn't have a intermediary state for its buttons or seekbars (which might be interesting to add in Gladys v4)
When the action isn't completed :

- the button switched back to its previous state
- the seekbar doesn't reset until another action made (from what I understand so far, I'll take more time to check my theory)

I'll close the issue if I don't find anything that might be related to the module :)

**Comment by atrovato** [comment]
I'm not sure Gladys V4 will handle this kind of behavior.
So I just did it now for the AwoX module.
If the light is OFF and you change the color, the light will be ON (on Gladys device page too).
Available ASAP.
