### ISSUE TITLE
Add Mesh Remote compatibility

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#12]

**Comment by atrovato** [comment]
The remote compatibility should be done on the configuration page, at first pairing action, and following this instructions : 
Reset the light (hold PowerOn + Fav. 1) and the remote (hold PowerOn + ColorCyicle) and connect the remote to the light again (hold PowerOn). Now hold PowerOn and the blue button for a few seconds, so the remote switches to Bluetooth-mode.

**Comment by atrovato** [comment]
I'll add this instructions directly on configuration page #23
