### ISSUE TITLE
Impossible to Switch from sequence to color/white mode

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#14]
Once you've setup a bulb, ON/OFF works fine, brightness too.
Selecting a sequence (rainbow etc.) works as well, but then it is impossible to go back to a single colour or white mode

Maybe a 3 states button in Gladys could be useful : 
- White (enable warm-cold picker, disable colour picker and sequence selector)
- Colour (enable colour picker, disable warm-cold picker, and sequence selector)
- Sequence (enable sequence selector, disable war-cold and colour pickers)

**Comment by atrovato** [comment]
To add the 3 states button in Gladys (or the enalbed/disabled behavior) I have to change the Gladys core, it's not about the AwoX module.
But now the color can be changed, so the color sequence can be stopped : it's a first step to disable the color sequence.
Still working on the white selector... 
Keep in touch.

**Comment by atrovato** [comment]
White is now available with the "white brightness" state.

**Comment by pebou** [comment]
It works like a charm ! 👍 
If you queue too many instructions it won't do everything and the system will crash but so far, so good 😃 
The issue now is the non-intuitive UI for selecting the color on the Gateway, but that one isn't up to you.
And now I have everything I need to control the lights via HTTP request in an Android app.
You did a really good job ! 🙂

**Comment by atrovato** [comment]
For the non intuitive UI, I think we should wait for Gladys v4 ;)
