### ISSUE TITLE
Filter bluetooth mac address'

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#16]
The bluetooth mac address of any Awox Mesh (can't say for the others) bulb starts with **a4:c1:38:** (supplyed by Telink Semiconductor). In order to improve configuration process, the module should only check status of devices with a mac address starting with a4:c1:38.

**Comment by atrovato** [comment]
Nice approach, but I'm not sure that all future devices MAC addresses will starts with a4:c1:38. Maybe AwoX will change it's constructor.
To be more compliant, I think the module should only check the "Manufacturer Name" provided by a BLE characteristic.
But today, the scan time is set to 15 seconds, I may minus it to 10 or 7 seconds, or maybe parametize it.
Do you agree ?

**Comment by pebou** [comment]
True, that's what i thought too. And you're right the manufacturer name should be enough.
I agree completely :)

**Comment by atrovato** [comment]
So, is the issue still open ? Or should I pretend to add the scan delay as a parameter ?

**Comment by pebou** [comment]
It can be closed, i don't think we need a scan delay at the moment, all my lights are detected whitin 15s
