### ISSUE TITLE
Differentiate already paired devices

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#28]
Currently, the  module will display every bulb it finds : 

- The unpaired ones
- The ones paired with Gladys (bulbs Gladys recognizes, and log into)
- The ones paired with the Awox App or another instance of Gladys (bulbs Gladys cannot log into)

It would be great if we could :

- Id each category easily with a text or an icon
- Disable the configuration button for the last two categories to avoid impossible pairings

**Comment by atrovato** [comment]
Ok, but for the last 2 categories, we may need to change user / pass for the network.
So it can be useful to keep this page (with a specific text / icon).
What do you think ?

**Comment by pebou** [comment]
I'm not sure to understand why you need to change user / pwd for the two last categories.
You'd like to keep the page displaying all the bulb status ?
