### ISSUE TITLE
Impossible to add a new bulb in Gladys

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#34]
After Analysis I try to configure the bulb setting a user/pwd but when i click on next nothing happens.
No log. Rebooting and reinstalling the module don't help. I'll try later to reinstall Gladys

**Comment by atrovato** [comment]
It's may be due to lasts commits. I'll check ASAP.

**Comment by atrovato** [comment]
It was due to an optimization to avoid complete loading at each message sent.
A condition didn't have any _else_, so the process was locked... then timeout... thne crash...
Now fixed ;)
