### ISSUE TITLE
Ajout du Bluetooth Mesh

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#4]
Bonjour,
Le module ne semble pas être compatible avec les Ampoules de la gamme Mesh. Serait-il possible d'ajouter cette prise en charge ?

En regardant ce qui se fait ailleurs, [Jeedom](https://github.com/jeedom/plugin-blea/commit/13aec6e4277e98027eb1ee20cf516d93414e05e5) propose dans son module BLEA une compatibilité au Bluetooth Mesh d'Awox, serait-il possible de s'en inspirer ?
JS n'est pas mon langage de prédilection, je ne suis pour l'instant pas en mesure de l'adapter ! Mais si quelqu'un s'y aventure ! Je lui serai infiniment reconnaissant ! 😃 
Merci d'avance ! :)

**Comment by atrovato** [comment]
Ok je regarderais, mais je n'ai pas de périphériques pour tester, je te demanderai d'être mon testeur ;)

**Comment by atrovato** [comment]
Salut, finalement j'ai craqué, je m'en suis commandé,  ce sera plus simple pour le développement. 
Il y a une petite offre sur Amazon https://www.amazon.fr/SKR2Lm-C9-E27-Smartlight-Connectées-Bluetooth-Télécommande/dp/B01L3C1VRY/ref=redir_mobile_desktop?_encoding=UTF8&psc=1&ref_=ya_aw_od_pi

**Comment by pebou** [comment]
Salut !

Ohohoh la belle promo ! Bon ok, je craque aussi, mon appartement va accueillir quelques ampoules supplémentaires ! C'est Noël avant l'heure ! 💡 🎅 

D'accord, hâte de voir ce que ça donne 🙂 
Si je peux aider, (pour la doc FR/EN ou autre, tant que ce n'est pas écrire du JS parce que pour l'instant je suis pas prêt 😛 ), je suis dispo !

**Comment by atrovato** [comment]
Bonjour,
je rencontre plusieurs problème concernant l'intégration du réseau Bluetooth Mesh.
Le plugin Jeedom se base sur une implémentation de Bluez (compatible Mesh) en Python, hors je ne parviens pas à mettre la main sur une implémentation (complète) de Bluez5 en JavaScript.

Je ne perds pas espoir, et continue mes investigations.

**Comment by pebou** [comment]
Salut,
D'accord ! Merci pour ces précisions sur ton avancement ! 👍 
J'espère que tu trouveras une bonne implémentation de la lib ou une autre lib le cas échéant !
J'en profite pour te poser une question : est-ce que tu comptes rendre les identifiants (username/password/key) paramétrable via des variables à personnaliser dans Gladys ?

Merci d'avance ! :)

**Comment by atrovato** [comment]
Salut,
Je t'avoue que je ne suis pas encore à ce niveau de réflexion, mais dans l'idéal ce serait top de rendre le module le plus paramétrable possible.
Je pense qu'il serait même utile de creer une issue spécifique sur le repo pour chaque idée notable, ainsi je n'oublierai rien ;)

**Comment by pebou** [comment]
Salut ! 
Je viens d'ajouter l'issue #7 pour les identifiants BT Mesh.
En fonction de ce qui existe déjà dans le module pour changer l'intensité, la couleur. Voici les quelques fonctionnalités qui me paraissent intéressante : 

- Gestion de la luminosité
- Gestion de la couleur RVB
- Gestion de la température blanc froid/chaud
- (facultatif) Gestion de la couleur TSL (ça peut être gérer par une app/lib externe qui convertit TSL>RVB)
- Effets (arc-en-ciel, transition en 2+ couleurs, dimming, heartbeat...) mais c'est peut-être plus facilement paramétrable avec un autre module ou en script ?
- Vérification régulière de l'état des ampoules (si mis à jour hors de Gladys, intervalle paramétrable)
- S'assurer que la commande est bien prise en compte par l'ampoule, tenter plusieurs fois de retransmettre l'information, le cas échéant (= retour d'état)

Qu'en penses-tu ? Je peux créer des issues pour chacun des points afin de les détailler :)

**Comment by atrovato** [comment]
Salut,
pour info, j'ai enfin réussi à m'identifier sur le réseau Mesh, et allumer et éteindre les ampoules.
Je suis en bonne voie.

Suite à tes dernières remarques, je préfère qu'une issue soit créée pour chaque élément, ce sera plus facile d'identifier les points réalisés et leurs bugs.

Je suis preneur de toute fonctionnalité utile, plus le module est complet, plus nous pourrons profiter pleinement de nos devices.

Merci pour ta présence, ça me motive d'avantage ;)

**Comment by atrovato** [comment]
Salut,
bonne nouvelle, la gestion des périphérique Mesh est en place, en version limitée pour le moment : 

- détection des périphériques
- configuration des identifiants
- gestion ON/OFF, luminosité
- bug sur la modification des couleurs

Les autres demandes seront traitées plus tard.
Have fun
