### ISSUE TITLE
Identify current color state of the bulb

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#40]
Add a param identifying if the bulb is in white or color (or sequence) mode

**Comment by atrovato** [comment]
A param or a device type as sensor ?

**Comment by pebou** [comment]
deviceType would be better :)

**Comment by atrovato** [comment]
Ok, a new device type is now created on configuration phase : mode.
(identifier = mode, type = mode, sensor = true, min = 1, max = 3)

As Gladys only handles decimal values, here is the suggested value mapping :
 1 = white
 2 = color
 3 = sequence
