### ISSUE TITLE
Bulb basic management

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#8]
The module should be able to manage the following bulb properties : 
- [x] ON/OFF
- [ ] Reachable (a light can be off, but still reachable)
- [x] Brightness
- [x] RGB colour (RGB/HSL)
- [x] White colour temperature (warm to cold white)
- [x] Name

**Comment by atrovato** [comment]
Hi, what do you mean with "Name" ?

**Comment by pebou** [comment]
The name you give to the device like desk lamp, roof light. It's not a properties stored in the bulb, but on gladys-side. And it seems it's already managed :)

**Comment by atrovato** [comment]
Ok, that's what I supposed ;)
Second point, I would like to check the RGB color point, but I feel suspicious about the HSL point... as Gladys only manage int values, the color is defined with an Integer, which is modified in a hex RGB (for BLE communication).
Can you explain me why/what is the HSL ? How do you plan to use it ?

**Comment by pebou** [comment]
HSL stands for Hue Saturation Lightness =(Brightness). In my opinion, it is much easier for the user to change the Hue and Saturation of its lights instead of juggling with R, G and B values.

**Comment by atrovato** [comment]
Hi,
another question, what do you mean with "Reachable (a light can be off, but still reachable)" ?
Today, you can set the color of the switched off light, this will swith it on in the selected color (for Mesh only).
I'm not sure to well understand.

**Comment by pebou** [comment]
Hi,
I mean that a light is reachable if it is detected by Gladys. So the light is at Bluetooth range and electrically powered on. In that case, the light can be off, but electrically on.
It is the same case as [your post](https://community.gladysassistant.com/t/parlons-de-gladys-v4/3578/216) on the Gladys forum about disabling a control if it is not reachable by the system.
